name: poc
description: "POC for GreenPacket"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #  store
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  #  localization
  easy_localization: ^3.0.7+1
  # dependency injection
  get_it: ^8.0.3
  #  navigation
  go_router: ^14.8.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
flutter:
  uses-material-design: true

  assets:
    - assets/lang/
